# Generated by Django 3.1.4 on 2023-01-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
